"""followers

Revision ID: 28648d559565
Revises: 26e6ddbcbc81
Create Date: 2019-03-10 00:51:24.928505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28648d559565'
down_revision = '26e6ddbcbc81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
